[package]
name = "ethereum-bls12"
version = "0.1.0"
authors = ["schaeff <thibaut@schaeff.fr>"]

[dependencies]
pairing = "0.14.2"
parity-bytes = { git = "https://github.com/paritytech/parity-common" }
rustc-hex = "1.0"